In [1]:
import pandas as pd

In [6]:
player = pd.read_csv('player_Oct2018.csv')
game = pd.read_csv('game_Oct2018.csv')
bet = pd.read_csv('Oct2018.csv')

In [7]:
player.head()

,Index,game_id,date,season,team,opp,starting_five,name,mp,fg,...,orbp,drbp,trbp,astp,stlp,blkp,tovp,usgp,ortg,drtg
0,0,201810160BOS,"8:00 PM, October 16, 2018",2019,Philadelphia 76ers,Boston Celtics,1,Ben Simmons,42:45,7.0,...,6.9,25.4,16.5,34.4,4.3,3.7,14.0,21.2,104.0,90.0
1,1,201810160BOS,"8:00 PM, October 16, 2018",2019,Philadelphia 76ers,Boston Celtics,1,Joel Embiid,36:49,9.0,...,5.3,19.7,12.8,11.7,1.3,4.3,17.7,32.5,84.0,98.0
2,2,201810160BOS,"8:00 PM, October 16, 2018",2019,Philadelphia 76ers,Boston Celtics,1,Robert Covington,34:12,3.0,...,2.9,13.2,8.3,0.0,2.7,2.3,16.7,14.9,67.0,99.0
3,3,201810160BOS,"8:00 PM, October 16, 2018",2019,Philadelphia 76ers,Boston Celtics,1,Markelle Fultz,24:20,2.0,...,0.0,11.2,5.8,13.1,1.9,0.0,27.6,19.0,52.0,103.0
4,4,201810160BOS,"8:00 PM, October 16, 2018",2019,Philadelphia 76ers,Boston Celtics,1,Dario Saric,22:55,3.0,...,0.0,23.7,12.3,7.6,0.0,0.0,27.3,20.4,55.0,103.0

In [8]:
game.head()

,Index,game_id,date,season,arena,away_name,home_name,pace,attendance,ref1,...,away_ortg,away_drtg,home_q1,home_q2,home_q3,home_q4,home_ot,home_final,home_ortg,home_drtg
0,0,201810160BOS,"8:00 PM, October 16, 2018",2019,"TD Garden, Boston, Massachusetts",Philadelphia 76ers,Boston Celtics,"18,624",104.3,Scott Foster,...,83.4,100.7,21,26,30,28,0,105,100.7,83.4
1,1,201810160GSW,"10:30 PM, October 16, 2018",2019,"Oracle Arena, Oakland, California",Oklahoma City Thunder,Golden State Warriors,"19,596",102.3,Brian Forte,...,97.7,105.6,31,26,26,25,0,108,105.6,97.7
2,2,201810170CHO,"7:00 PM, October 17, 2018",2019,"Spectrum Center, Charlotte, North Carolina",Milwaukee Bucks,Charlotte Hornets,"17,889",102.6,Sean Corbin,...,110.2,109.2,23,31,29,29,0,112,109.2,110.2
3,3,201810170DET,"7:00 PM, October 17, 2018",2019,"Little Caesars Arena, Detroit, Michigan",Brooklyn Nets,Detroit Pistons,"20,332",100.0,Eric Dalen,...,100.0,103.0,24,27,32,20,0,103,103.0,100.0
4,4,201810170HOU,"8:00 PM, October 17, 2018",2019,"Toyota Center, Houston, Texas",New Orleans Pelicans,Houston Rockets,"18,055",103.0,Curtis Blair,...,127.2,108.8,29,25,30,28,0,112,108.8,127.2

In [9]:
bet.head()

,Index,date,bet,length,game_num,aw,hw,ao,ho,ab1,...,ab6,hb6,ab7,hb7,ab8,hb8,ab9,hb9,ab10,hb10
0,0,20181016,p,full,0,45%,55%,+5-110,-5-110,+4Â½-101,...,+4Â½-105,-4Â½-105,+5-110,-5-110,+4Â½-110,-4Â½-110,+4Â½-110,-4Â½-110,+4Â½-110,-4Â½-110
1,1,20181016,p,full,1,42%,58%,+12-110,-12-110,+12Â½+102,...,+12Â½-105,-12Â½-105,+13-105,-13-115,+13-110,-13-110,+12-107,-12-113,+12Â½-105,-12Â½-115
2,2,20181016,p,first,0,45%,55%,+2Â½-110,-2Â½-110,+2Â½-107,...,+3-115,-3-105,+3-115,-3-105,+3-115,-3-105,+2Â½-115,-2Â½-105,+2Â½-110,-2Â½-110
3,3,20181016,p,first,1,42%,58%,+7-110,-7-110,+7Â½-102,...,+7Â½-105,-7Â½-115,+7Â½-105,-7Â½-115,+8-110,-8-110,+7Â½-110,-7Â½-110,+7Â½-110,-7Â½-110
4,4,20181016,p,sec,0,49%,51%,+1-110,-1-110,-,...,+1-115,-1-105,+1-110,-1-110,-,-,+1-110,-1-110,+1-115,-1-105

In [16]:
# build team first
team_list = game.away_name.unique()
team_look_up_table = {}
for idx, el in enumerate(team_list):
    print('INSERT INTO team VALUES(' + str(idx+1), ',\'' + el + '\');')
    team_look_up_table[el]=idx+1

INSERT INTO team VALUES(1 ,'Philadelphia 76ers');
INSERT INTO team VALUES(2 ,'Oklahoma City Thunder');
INSERT INTO team VALUES(3 ,'Milwaukee Bucks');
INSERT INTO team VALUES(4 ,'Brooklyn Nets');
INSERT INTO team VALUES(5 ,'New Orleans Pelicans');
INSERT INTO team VALUES(6 ,'Memphis Grizzlies');
INSERT INTO team VALUES(7 ,'Denver Nuggets');
INSERT INTO team VALUES(8 ,'Atlanta Hawks');
INSERT INTO team VALUES(9 ,'Miami Heat');
INSERT INTO team VALUES(10 ,'Dallas Mavericks');
INSERT INTO team VALUES(11 ,'Utah Jazz');
INSERT INTO team VALUES(12 ,'Minnesota Timberwolves');
INSERT INTO team VALUES(13 ,'Cleveland Cavaliers');
INSERT INTO team VALUES(14 ,'Chicago Bulls');
INSERT INTO team VALUES(15 ,'Los Angeles Lakers');
INSERT INTO team VALUES(16 ,'New York Knicks');
INSERT INTO team VALUES(17 ,'Indiana Pacers');
INSERT INTO team VALUES(18 ,'Sacramento Kings');
INSERT INTO team VALUES(19 ,'Charlotte Hornets');
INSERT INTO team VALUES(20 ,'Boston Celtics');
INSERT INTO team VALUES(21 ,'Golden State Warriors');
INSERT INTO team VALUES(22 ,'Detroit Pistons');
INSERT INTO team VALUES(23 ,'Phoenix Suns');
INSERT INTO team VALUES(24 ,'Houston Rockets');
INSERT INTO team VALUES(25 ,'Orlando Magic');
INSERT INTO team VALUES(26 ,'San Antonio Spurs');
INSERT INTO team VALUES(27 ,'Toronto Raptors');
INSERT INTO team VALUES(28 ,'Washington Wizards');
INSERT INTO team VALUES(29 ,'Los Angeles Clippers');
INSERT INTO team VALUES(30 ,'Portland Trail Blazers');

In [30]:
# build player
name_list = player.name.unique()
player_look_up_table = {}
for idx, el in enumerate(name_list):
    try: 
        first, last = el.split()
        print('INSERT INTO player VALUES(' + str(idx+1) + ',\'' + first + '\',\'' + last +'\');')
        player_look_up_table[el] = idx + 1
    except:
        print(el)

INSERT INTO player VALUES(1,'Ben','Simmons');
INSERT INTO player VALUES(2,'Joel','Embiid');
INSERT INTO player VALUES(3,'Robert','Covington');
INSERT INTO player VALUES(4,'Markelle','Fultz');
INSERT INTO player VALUES(5,'Dario','Saric');
INSERT INTO player VALUES(6,'J.J.','Redick');
INSERT INTO player VALUES(7,'T.J.','McConnell');
INSERT INTO player VALUES(8,'Landry','Shamet');
INSERT INTO player VALUES(9,'Amir','Johnson');
INSERT INTO player VALUES(10,'Furkan','Korkmaz');
INSERT INTO player VALUES(11,'Jonah','Bolden');
INSERT INTO player VALUES(12,'Demetrius','Jackson');
INSERT INTO player VALUES(13,'Shake','Milton');
INSERT INTO player VALUES(14,'Al','Horford');
INSERT INTO player VALUES(15,'Kyrie','Irving');
INSERT INTO player VALUES(16,'Jayson','Tatum');
INSERT INTO player VALUES(17,'Jaylen','Brown');
INSERT INTO player VALUES(18,'Gordon','Hayward');
INSERT INTO player VALUES(19,'Terry','Rozier');
INSERT INTO player VALUES(20,'Marcus','Smart');
INSERT INTO player VALUES(21,'Marcus','Morris');
INSERT INTO player VALUES(22,'Aron','Baynes');
INSERT INTO player VALUES(23,'Daniel','Theis');
INSERT INTO player VALUES(24,'Semi','Ojeleye');
INSERT INTO player VALUES(25,'Guerschon','Yabusele');
INSERT INTO player VALUES(26,'Brad','Wanamaker');
INSERT INTO player VALUES(27,'Paul','George');
INSERT INTO player VALUES(28,'Steven','Adams');
INSERT INTO player VALUES(29,'Dennis','Schroder');
INSERT INTO player VALUES(30,'Terrance','Ferguson');
INSERT INTO player VALUES(31,'Patrick','Patterson');
INSERT INTO player VALUES(32,'Jerami','Grant');
INSERT INTO player VALUES(33,'Alex','Abrines');
INSERT INTO player VALUES(34,'Raymond','Felton');
INSERT INTO player VALUES(35,'Nerlens','Noel');
INSERT INTO player VALUES(36,'Hamidou','Diallo');
INSERT INTO player VALUES(37,'Deonte','Burton');
INSERT INTO player VALUES(38,'Abdel','Nader');
INSERT INTO player VALUES(39,'Timothe','Luwawu-Cabarrot');
INSERT INTO player VALUES(40,'Kevin','Durant');
INSERT INTO player VALUES(41,'Stephen','Curry');
INSERT INTO player VALUES(42,'Klay','Thompson');
INSERT INTO player VALUES(43,'Draymond','Green');
INSERT INTO player VALUES(44,'Damian','Jones');
INSERT INTO player VALUES(45,'Kevon','Looney');
INSERT INTO player VALUES(46,'Shaun','Livingston');
INSERT INTO player VALUES(47,'Quinn','Cook');
INSERT INTO player VALUES(48,'Andre','Iguodala');
INSERT INTO player VALUES(49,'Jordan','Bell');
INSERT INTO player VALUES(50,'Jonas','Jerebko');
INSERT INTO player VALUES(51,'Alfonzo','McKinnie');
INSERT INTO player VALUES(52,'Jacob','Evans');
INSERT INTO player VALUES(53,'Malcolm','Brogdon');
INSERT INTO player VALUES(54,'Giannis','Antetokounmpo');
INSERT INTO player VALUES(55,'Eric','Bledsoe');
INSERT INTO player VALUES(56,'Khris','Middleton');
INSERT INTO player VALUES(57,'Brook','Lopez');
INSERT INTO player VALUES(58,'Ersan','Ilyasova');
INSERT INTO player VALUES(59,'Donte','DiVincenzo');
INSERT INTO player VALUES(60,'John','Henson');
INSERT INTO player VALUES(61,'Tony','Snell');
INSERT INTO player VALUES(62,'Christian','Wood');
INSERT INTO player VALUES(63,'Sterling','Brown');
INSERT INTO player VALUES(64,'Pat','Connaughton');
INSERT INTO player VALUES(65,'Matthew','Dellavedova');
INSERT INTO player VALUES(66,'Kemba','Walker');
INSERT INTO player VALUES(67,'Nicolas','Batum');
INSERT INTO player VALUES(68,'Marvin','Williams');
INSERT INTO player VALUES(69,'Cody','Zeller');
INSERT INTO player VALUES(70,'Jeremy','Lamb');
INSERT INTO player VALUES(71,'Malik','Monk');
INSERT INTO player VALUES(72,'Michael','Kidd-Gilchrist');
INSERT INTO player VALUES(73,'Tony','Parker');
INSERT INTO player VALUES(74,'Miles','Bridges');
INSERT INTO player VALUES(75,'Willy','Hernangomez');
INSERT INTO player VALUES(76,'Bismack','Biyombo');
INSERT INTO player VALUES(77,'Dwayne','Bacon');
INSERT INTO player VALUES(78,'Frank','Kaminsky');
INSERT INTO player VALUES(79,'Joe','Harris');
INSERT INTO player VALUES(80,'Jared','Dudley');
INSERT INTO player VALUES(81,'Caris','LeVert');
INSERT INTO player VALUES(82,'Jarrett','Allen');
INSERT INTO player VALUES(83,'D'Angelo','Russell');
INSERT INTO player VALUES(84,'Spencer','Dinwiddie');
INSERT INTO player VALUES(85,'Ed','Davis');
INSERT INTO player VALUES(86,'Treveon','Graham');
INSERT INTO player VALUES(87,'Rodions','Kurucs');
INSERT INTO player VALUES(88,'Dzanan','Musa');
INSERT INTO player VALUES(89,'Theo','Pinson');
INSERT INTO player VALUES(90,'Kenneth','Faried');
INSERT INTO player VALUES(91,'Reggie','Jackson');
INSERT INTO player VALUES(92,'Blake','Griffin');
INSERT INTO player VALUES(93,'Andre','Drummond');
INSERT INTO player VALUES(94,'Luke','Kennard');
INSERT INTO player VALUES(95,'Bruce','Brown');
INSERT INTO player VALUES(96,'Langston','Galloway');
INSERT INTO player VALUES(97,'Ish','Smith');
INSERT INTO player VALUES(98,'Glenn','Robinson');
INSERT INTO player VALUES(99,'Zaza','Pachulia');
INSERT INTO player VALUES(100,'Zach','Lofton');
INSERT INTO player VALUES(101,'Jose','Calderon');
INSERT INTO player VALUES(102,'Reggie','Bullock');
INSERT INTO player VALUES(103,'Stanley','Johnson');
INSERT INTO player VALUES(104,'Jon','Leuer');
INSERT INTO player VALUES(105,'Henry','Ellenson');
INSERT INTO player VALUES(106,'Anthony','Davis');
INSERT INTO player VALUES(107,'Jrue','Holiday');
INSERT INTO player VALUES(108,'Elfrid','Payton');
INSERT INTO player VALUES(109,'E'Twaun','Moore');
INSERT INTO player VALUES(110,'Nikola','Mirotic');
INSERT INTO player VALUES(111,'Julius','Randle');
INSERT INTO player VALUES(112,'Darius','Miller');
INSERT INTO player VALUES(113,'Solomon','Hill');
INSERT INTO player VALUES(114,'Jahlil','Okafor');
INSERT INTO player VALUES(115,'Kenrich','Williams');
INSERT INTO player VALUES(116,'Cheick','Diallo');
INSERT INTO player VALUES(117,'Frank','Jackson');
INSERT INTO player VALUES(118,'Ian','Clark');
INSERT INTO player VALUES(119,'James','Harden');
INSERT INTO player VALUES(120,'P.J.','Tucker');
INSERT INTO player VALUES(121,'Chris','Paul');
INSERT INTO player VALUES(122,'Clint','Capela');
INSERT INTO player VALUES(123,'James','Ennis');
INSERT INTO player VALUES(124,'Eric','Gordon');
INSERT INTO player VALUES(125,'Carmelo','Anthony');
INSERT INTO player VALUES(126,'Michael','Carter-Williams');
INSERT INTO player VALUES(127,'Gerald','Green');
INSERT INTO player VALUES(128,'Isaiah','Hartenstein');
INSERT INTO player VALUES(129,'Gary','Clark');
INSERT INTO player VALUES(130,'Marc','Gasol');
INSERT INTO player VALUES(131,'Mike','Conley');
INSERT INTO player VALUES(132,'JaMychal','Green');
INSERT INTO player VALUES(133,'Garrett','Temple');
INSERT INTO player VALUES(134,'Chandler','Parsons');
INSERT INTO player VALUES(135,'Shelvin','Mack');
INSERT INTO player VALUES(136,'Jaren','Jackson');
INSERT INTO player VALUES(137,'MarShon','Brooks');
INSERT INTO player VALUES(138,'Kyle','Anderson');
INSERT INTO player VALUES(139,'Dillon','Brooks');
INSERT INTO player VALUES(140,'Wayne','Selden');
INSERT INTO player VALUES(141,'Omri','Casspi');
INSERT INTO player VALUES(142,'Ivan','Rabb');
INSERT INTO player VALUES(143,'Thaddeus','Young');
INSERT INTO player VALUES(144,'Bojan','Bogdanovic');
INSERT INTO player VALUES(145,'Victor','Oladipo');
INSERT INTO player VALUES(146,'Darren','Collison');
INSERT INTO player VALUES(147,'Myles','Turner');
INSERT INTO player VALUES(148,'Domantas','Sabonis');
INSERT INTO player VALUES(149,'Cory','Joseph');
INSERT INTO player VALUES(150,'Doug','McDermott');
INSERT INTO player VALUES(151,'Tyreke','Evans');
INSERT INTO player VALUES(152,'Aaron','Holiday');
INSERT INTO player VALUES(153,'Kyle','O'Quinn');
INSERT INTO player VALUES(154,'Edmond','Sumner');
INSERT INTO player VALUES(155,'T.J.','Leaf');
INSERT INTO player VALUES(156,'Will','Barton');
INSERT INTO player VALUES(157,'Gary','Harris');
INSERT INTO player VALUES(158,'Nikola','Jokic');
INSERT INTO player VALUES(159,'Jamal','Murray');
INSERT INTO player VALUES(160,'Paul','Millsap');
INSERT INTO player VALUES(161,'Trey','Lyles');
INSERT INTO player VALUES(162,'Monte','Morris');
INSERT INTO player VALUES(163,'Juan','Hernangomez');
INSERT INTO player VALUES(164,'Mason','Plumlee');
INSERT INTO player VALUES(165,'Malik','Beasley');
INSERT INTO player VALUES(166,'Thomas','Welsh');
INSERT INTO player VALUES(167,'Tyler','Lydon');
INSERT INTO player VALUES(168,'Torrey','Craig');
INSERT INTO player VALUES(169,'Tobias','Harris');
INSERT INTO player VALUES(170,'Danilo','Gallinari');
INSERT INTO player VALUES(171,'Avery','Bradley');
INSERT INTO player VALUES(172,'Patrick','Beverley');
INSERT INTO player VALUES(173,'Marcin','Gortat');
INSERT INTO player VALUES(174,'Shai','Gilgeous-Alexander');
INSERT INTO player VALUES(175,'Lou','Williams');
INSERT INTO player VALUES(176,'Boban','Marjanovic');
INSERT INTO player VALUES(177,'Montrezl','Harrell');
Luc Mbah a Moute
INSERT INTO player VALUES(179,'Mike','Scott');
INSERT INTO player VALUES(180,'Tyrone','Wallace');
INSERT INTO player VALUES(181,'Jerome','Robinson');
INSERT INTO player VALUES(182,'Trae','Young');
INSERT INTO player VALUES(183,'Taurean','Waller-Prince');
INSERT INTO player VALUES(184,'Kent','Bazemore');
INSERT INTO player VALUES(185,'Vince','Carter');
INSERT INTO player VALUES(186,'Alex','Len');
INSERT INTO player VALUES(187,'DeAndre'','Bembry');
INSERT INTO player VALUES(188,'Alex','Poythress');
INSERT INTO player VALUES(189,'Tyler','Dorsey');
INSERT INTO player VALUES(190,'Jeremy','Lin');
INSERT INTO player VALUES(191,'Miles','Plumlee');
INSERT INTO player VALUES(192,'Omari','Spellman');
INSERT INTO player VALUES(193,'Kevin','Huerter');
INSERT INTO player VALUES(194,'Jaylen','Adams');
INSERT INTO player VALUES(195,'Frank','Ntilikina');
INSERT INTO player VALUES(196,'Tim','Hardaway');
INSERT INTO player VALUES(197,'Enes','Kanter');
INSERT INTO player VALUES(198,'Trey','Burke');
INSERT INTO player VALUES(199,'Lance','Thomas');
INSERT INTO player VALUES(200,'Ron','Baker');
INSERT INTO player VALUES(201,'Allonzo','Trier');
INSERT INTO player VALUES(202,'Kevin','Knox');
INSERT INTO player VALUES(203,'Mario','Hezonja');
INSERT INTO player VALUES(204,'Noah','Vonleh');
INSERT INTO player VALUES(205,'Mitchell','Robinson');
INSERT INTO player VALUES(206,'Damyean','Dotson');
INSERT INTO player VALUES(207,'Courtney','Lee');
INSERT INTO player VALUES(208,'Josh','Richardson');
INSERT INTO player VALUES(209,'Hassan','Whiteside');
INSERT INTO player VALUES(210,'Goran','Dragic');
INSERT INTO player VALUES(211,'Rodney','McGruder');
INSERT INTO player VALUES(212,'Derrick','Jones');
INSERT INTO player VALUES(213,'Dwyane','Wade');
INSERT INTO player VALUES(214,'Tyler','Johnson');
INSERT INTO player VALUES(215,'Bam','Adebayo');
INSERT INTO player VALUES(216,'Kelly','Olynyk');
INSERT INTO player VALUES(217,'Yante','Maten');
INSERT INTO player VALUES(218,'Duncan','Robinson');
INSERT INTO player VALUES(219,'Udonis','Haslem');
INSERT INTO player VALUES(220,'Wayne','Ellington');
INSERT INTO player VALUES(221,'Aaron','Gordon');
INSERT INTO player VALUES(222,'Nikola','Vucevic');
INSERT INTO player VALUES(223,'Evan','Fournier');
INSERT INTO player VALUES(224,'D.J.','Augustin');
INSERT INTO player VALUES(225,'Jonathan','Isaac');
INSERT INTO player VALUES(226,'Jonathon','Simmons');
INSERT INTO player VALUES(227,'Jerian','Grant');
INSERT INTO player VALUES(228,'Terrence','Ross');
INSERT INTO player VALUES(229,'Mohamed','Bamba');
INSERT INTO player VALUES(230,'Wesley','Iwundu');
INSERT INTO player VALUES(231,'Isaiah','Briscoe');
INSERT INTO player VALUES(232,'Khem','Birch');
INSERT INTO player VALUES(233,'Jarell','Martin');
INSERT INTO player VALUES(234,'Wesley','Matthews');
INSERT INTO player VALUES(235,'Luka','Doncic');
INSERT INTO player VALUES(236,'DeAndre','Jordan');
INSERT INTO player VALUES(237,'Dorian','Finney-Smith');
INSERT INTO player VALUES(238,'Dennis','Smith');
INSERT INTO player VALUES(239,'J.J.','Barea');
INSERT INTO player VALUES(240,'Jalen','Brunson');
INSERT INTO player VALUES(241,'Dwight','Powell');
INSERT INTO player VALUES(242,'Maxi','Kleber');
INSERT INTO player VALUES(243,'Devin','Harris');
INSERT INTO player VALUES(244,'Ryan','Broekhoff');
INSERT INTO player VALUES(245,'Ray','Spalding');
INSERT INTO player VALUES(246,'Salah','Mejri');
INSERT INTO player VALUES(247,'Trevor','Ariza');
INSERT INTO player VALUES(248,'Deandre','Ayton');
INSERT INTO player VALUES(249,'Isaiah','Canaan');
INSERT INTO player VALUES(250,'Devin','Booker');
INSERT INTO player VALUES(251,'Ryan','Anderson');
INSERT INTO player VALUES(252,'Josh','Jackson');
INSERT INTO player VALUES(253,'T.J.','Warren');
INSERT INTO player VALUES(254,'Tyson','Chandler');
INSERT INTO player VALUES(255,'Elie','Okobo');
INSERT INTO player VALUES(256,'Troy','Daniels');
INSERT INTO player VALUES(257,'Mikal','Bridges');
INSERT INTO player VALUES(258,'Richaun','Holmes');
INSERT INTO player VALUES(259,'Dragan','Bender');
INSERT INTO player VALUES(260,'Rudy','Gobert');
INSERT INTO player VALUES(261,'Donovan','Mitchell');
INSERT INTO player VALUES(262,'Joe','Ingles');
INSERT INTO player VALUES(263,'Derrick','Favors');
INSERT INTO player VALUES(264,'Ricky','Rubio');
INSERT INTO player VALUES(265,'Jae','Crowder');
INSERT INTO player VALUES(266,'Dante','Exum');
INSERT INTO player VALUES(267,'Alec','Burks');
INSERT INTO player VALUES(268,'Royce','O'Neale');
INSERT INTO player VALUES(269,'Georges','Niang');
INSERT INTO player VALUES(270,'Ekpe','Udoh');
INSERT INTO player VALUES(271,'Grayson','Allen');
INSERT INTO player VALUES(272,'Willie','Cauley-Stein');
INSERT INTO player VALUES(273,'De'Aaron','Fox');
INSERT INTO player VALUES(274,'Buddy','Hield');
INSERT INTO player VALUES(275,'Yogi','Ferrell');
INSERT INTO player VALUES(276,'Nemanja','Bjelica');
INSERT INTO player VALUES(277,'Justin','Jackson');
INSERT INTO player VALUES(278,'Iman','Shumpert');
INSERT INTO player VALUES(279,'Marvin','Bagley');
INSERT INTO player VALUES(280,'Harry','Giles');
INSERT INTO player VALUES(281,'Frank','Mason');
INSERT INTO player VALUES(282,'Skal','Labissiere');
INSERT INTO player VALUES(283,'Ben','McLemore');
INSERT INTO player VALUES(284,'Wenyen','Gabriel');
INSERT INTO player VALUES(285,'Andrew','Wiggins');
INSERT INTO player VALUES(286,'Jimmy','Butler');
INSERT INTO player VALUES(287,'Jeff','Teague');
INSERT INTO player VALUES(288,'Taj','Gibson');
INSERT INTO player VALUES(289,'Karl-Anthony','Towns');
INSERT INTO player VALUES(290,'Derrick','Rose');
INSERT INTO player VALUES(291,'Gorgui','Dieng');
INSERT INTO player VALUES(292,'Anthony','Tolliver');
INSERT INTO player VALUES(293,'Tyus','Jones');
INSERT INTO player VALUES(294,'Josh','Okogie');
INSERT INTO player VALUES(295,'Keita','Bates-Diop');
INSERT INTO player VALUES(296,'Luol','Deng');
INSERT INTO player VALUES(297,'James','Nunnally');
INSERT INTO player VALUES(298,'LaMarcus','Aldridge');
INSERT INTO player VALUES(299,'DeMar','DeRozan');
INSERT INTO player VALUES(300,'Bryn','Forbes');
INSERT INTO player VALUES(301,'Rudy','Gay');
INSERT INTO player VALUES(302,'Jakob','Poeltl');
INSERT INTO player VALUES(303,'Patty','Mills');
INSERT INTO player VALUES(304,'Pau','Gasol');
INSERT INTO player VALUES(305,'Marco','Belinelli');
INSERT INTO player VALUES(306,'Davis','Bertans');
INSERT INTO player VALUES(307,'Dante','Cunningham');
INSERT INTO player VALUES(308,'Drew','Eubanks');
INSERT INTO player VALUES(309,'Quincy','Pondexter');
INSERT INTO player VALUES(310,'Chimezie','Metu');
INSERT INTO player VALUES(311,'Kevin','Love');
INSERT INTO player VALUES(312,'Cedi','Osman');
INSERT INTO player VALUES(313,'George','Hill');
INSERT INTO player VALUES(314,'Tristan','Thompson');
INSERT INTO player VALUES(315,'Rodney','Hood');
INSERT INTO player VALUES(316,'Jordan','Clarkson');
INSERT INTO player VALUES(317,'Collin','Sexton');
INSERT INTO player VALUES(318,'Sam','Dekker');
INSERT INTO player VALUES(319,'Ante','Zizic');
INSERT INTO player VALUES(320,'Kyle','Korver');
INSERT INTO player VALUES(321,'David','Nwaba');
INSERT INTO player VALUES(322,'John','Holland');
INSERT INTO player VALUES(323,'Channing','Frye');
INSERT INTO player VALUES(324,'Kawhi','Leonard');
INSERT INTO player VALUES(325,'Kyle','Lowry');
INSERT INTO player VALUES(326,'Danny','Green');
INSERT INTO player VALUES(327,'Jonas','Valanciunas');
INSERT INTO player VALUES(328,'Pascal','Siakam');
INSERT INTO player VALUES(329,'Serge','Ibaka');
INSERT INTO player VALUES(330,'Fred','VanVleet');
INSERT INTO player VALUES(331,'OG','Anunoby');
INSERT INTO player VALUES(332,'Norman','Powell');
INSERT INTO player VALUES(333,'C.J.','Miles');
INSERT INTO player VALUES(334,'Lorenzo','Brown');
INSERT INTO player VALUES(335,'Malachi','Richardson');
INSERT INTO player VALUES(336,'Greg','Monroe');
INSERT INTO player VALUES(337,'Bobby','Portis');
INSERT INTO player VALUES(338,'Zach','LaVine');
INSERT INTO player VALUES(339,'Justin','Holiday');
INSERT INTO player VALUES(340,'Cameron','Payne');
INSERT INTO player VALUES(341,'Wendell','Carter');
INSERT INTO player VALUES(342,'Antonio','Blakeney');
INSERT INTO player VALUES(343,'Ryan','Arcidiacono');
INSERT INTO player VALUES(344,'Jabari','Parker');
INSERT INTO player VALUES(345,'Robin','Lopez');
INSERT INTO player VALUES(346,'Chandler','Hutchison');
INSERT INTO player VALUES(347,'Tyler','Ulis');
INSERT INTO player VALUES(348,'Rawle','Alkins');
INSERT INTO player VALUES(349,'LeBron','James');
INSERT INTO player VALUES(350,'Rajon','Rondo');
INSERT INTO player VALUES(351,'Brandon','Ingram');
INSERT INTO player VALUES(352,'Kentavious','Caldwell-Pope');
INSERT INTO player VALUES(353,'JaVale','McGee');
INSERT INTO player VALUES(354,'Kyle','Kuzma');
INSERT INTO player VALUES(355,'Josh','Hart');
INSERT INTO player VALUES(356,'Lonzo','Ball');
INSERT INTO player VALUES(357,'Lance','Stephenson');
INSERT INTO player VALUES(358,'Michael','Beasley');
INSERT INTO player VALUES(359,'Ivica','Zubac');
INSERT INTO player VALUES(360,'Sviatoslav','Mykhailiuk');
INSERT INTO player VALUES(361,'Isaac','Bonga');
INSERT INTO player VALUES(362,'Damian','Lillard');
INSERT INTO player VALUES(363,'CJ','McCollum');
INSERT INTO player VALUES(364,'Al-Farouq','Aminu');
INSERT INTO player VALUES(365,'Jusuf','Nurkic');
INSERT INTO player VALUES(366,'Jake','Layman');
INSERT INTO player VALUES(367,'Nik','Stauskas');
INSERT INTO player VALUES(368,'Zach','Collins');
INSERT INTO player VALUES(369,'Evan','Turner');
INSERT INTO player VALUES(370,'Maurice','Harkless');
INSERT INTO player VALUES(371,'Seth','Curry');
INSERT INTO player VALUES(372,'Meyers','Leonard');
INSERT INTO player VALUES(373,'Wade','Baldwin');
INSERT INTO player VALUES(374,'Caleb','Swanigan');
INSERT INTO player VALUES(375,'John','Wall');
INSERT INTO player VALUES(376,'Otto','Porter');
INSERT INTO player VALUES(377,'Bradley','Beal');
INSERT INTO player VALUES(378,'Markieff','Morris');
INSERT INTO player VALUES(379,'Ian','Mahinmi');
INSERT INTO player VALUES(380,'Jeff','Green');
INSERT INTO player VALUES(381,'Austin','Rivers');
INSERT INTO player VALUES(382,'Kelly','Oubre');
INSERT INTO player VALUES(383,'Jason','Smith');
INSERT INTO player VALUES(384,'Tomas','Satoransky');
INSERT INTO player VALUES(385,'Jordan','McRae');
INSERT INTO player VALUES(386,'Thomas','Bryant');
INSERT INTO player VALUES(387,'Troy','Brown');
INSERT INTO player VALUES(388,'Luke','Kornet');
INSERT INTO player VALUES(389,'Allen','Crabbe');
INSERT INTO player VALUES(390,'Milos','Teodosic');
INSERT INTO player VALUES(391,'Andrew','Harrison');
INSERT INTO player VALUES(392,'Alize','Johnson');
INSERT INTO player VALUES(393,'J.R.','Smith');
INSERT INTO player VALUES(394,'Tim','Frazier');
INSERT INTO player VALUES(395,'Damion','Lee');
INSERT INTO player VALUES(396,'Cristiano','Felicio');
INSERT INTO player VALUES(397,'C.J.','Williams');
INSERT INTO player VALUES(398,'Daryl','Macon');
INSERT INTO player VALUES(399,'Jamal','Crawford');
INSERT INTO player VALUES(400,'Ike','Anigbogu');
INSERT INTO player VALUES(401,'Nene','Hilario');
INSERT INTO player VALUES(402,'Johnathan','Williams');
INSERT INTO player VALUES(403,'Devonte'','Graham');

In [85]:
for index, el in game.iterrows():
    print('INSERT INTO game VALUES(' + 
          el.game_id + ',' +
          el.date.replace(',','') + ',' +
          str(team_look_up_table[str(el.away_name)]) + ',' +
          str(team_look_up_table[str(el.home_name)]) + ',' +
          str(el.home_q1)+ ',' +
          str(el.home_q2)+ ',' +
          str(el.home_q3)+ ',' +
          str(el.home_q4)+ ',' +
          str(el.away_q1)+ ',' +
          str(el.away_q2)+ ',' +
          str(el.away_q3)+ ',' +
          str(el.away_q4)+ ',' +
          str(el.home_ot)+ ',' +
          str(el.away_ot) + ');'
         )

INSERT INTO game VALUES(201810160BOS,8:00 PM October 16 2018,1,20,21,26,30,28,21,21,24,21,0,0);
INSERT INTO game VALUES(201810160GSW,10:30 PM October 16 2018,2,21,31,26,26,25,23,24,32,21,0,0);
INSERT INTO game VALUES(201810170CHO,7:00 PM October 17 2018,3,19,23,31,29,29,36,31,26,20,0,0);
INSERT INTO game VALUES(201810170DET,7:00 PM October 17 2018,4,22,24,27,32,20,29,22,25,24,0,0);
INSERT INTO game VALUES(201810170HOU,8:00 PM October 17 2018,5,24,29,25,30,28,35,36,30,30,0,0);
INSERT INTO game VALUES(201810170IND,7:00 PM October 17 2018,6,17,27,29,20,35,16,23,19,25,0,0);
INSERT INTO game VALUES(201810170LAC,10:30 PM October 17 2018,7,29,24,30,18,26,29,30,15,33,0,0);
INSERT INTO game VALUES(201810170NYK,7:30 PM October 17 2018,8,16,23,49,34,20,24,25,35,23,0,0);
INSERT INTO game VALUES(201810170ORL,7:00 PM October 17 2018,9,25,25,29,25,25,31,20,27,23,0,0);
INSERT INTO game VALUES(201810170PHO,10:30 PM October 17 2018,10,23,37,19,27,38,24,22,27,27,0,0);
INSERT INTO game VALUES(201810170SAC,10:00 PM October 17 2018,11,18,34,21,32,30,30,38,25,30,0,0);
INSERT INTO game VALUES(201810170SAS,8:30 PM October 17 2018,12,26,31,25,25,31,23,29,31,25,0,0);
INSERT INTO game VALUES(201810170TOR,7:30 PM October 17 2018,13,27,28,32,30,26,25,22,28,29,0,0);
INSERT INTO game VALUES(201810180PHI,8:00 PM October 18 2018,14,1,38,27,37,25,41,17,18,32,0,0);
INSERT INTO game VALUES(201810180POR,10:30 PM October 18 2018,15,30,34,31,28,35,31,32,28,28,0,0);
INSERT INTO game VALUES(201810180WAS,8:00 PM October 18 2018,9,28,25,34,30,23,24,34,27,28,0,0);
INSERT INTO game VALUES(201810190BRK,7:30 PM October 19 2018,16,4,33,24,17,33,24,26,26,29,0,0);
INSERT INTO game VALUES(201810190LAC,10:30 PM October 19 2018,2,29,27,21,23,37,20,26,31,15,0,0);
INSERT INTO game VALUES(201810190MEM,8:00 PM October 19 2018,8,6,37,40,29,25,33,28,21,35,0,0);
INSERT INTO game VALUES(201810190MIL,8:30 PM October 19 2018,17,3,30,32,31,25,25,28,23,25,0,0);
INSERT INTO game VALUES(201810190MIN,8:00 PM October 19 2018,13,12,32,39,33,27,30,24,41,28,0,0);
INSERT INTO game VALUES(201810190NOP,8:00 PM October 19 2018,18,5,40,32,38,39,32,31,27,39,0,0);
INSERT INTO game VALUES(201810190ORL,7:00 PM October 19 2018,19,25,10,21,23,34,22,29,31,38,0,0);
INSERT INTO game VALUES(201810190TOR,8:00 PM October 19 2018,20,27,18,31,33,31,25,28,26,22,0,0);
INSERT INTO game VALUES(201810190UTA,10:30 PM October 19 2018,21,11,34,47,22,20,32,37,28,27,0,0);
INSERT INTO game VALUES(201810200CHI,8:00 PM October 20 2018,22,14,27,31,26,32,25,35,25,33,0,0);
INSERT INTO game VALUES(201810200DAL,8:30 PM October 20 2018,12,10,37,32,28,43,46,23,30,37,0,0);
INSERT INTO game VALUES(201810200DEN,9:00 PM October 20 2018,23,7,30,35,27,27,16,33,30,12,0,0);
INSERT INTO game VALUES(201810200IND,7:00 PM October 20 2018,4,17,33,34,28,37,29,29,27,27,0,0);
INSERT INTO game VALUES(201810200LAL,10:30 PM October 20 2018,24,15,28,34,35,18,31,35,32,26,0,0);
INSERT INTO game VALUES(201810200MIA,8:00 PM October 20 2018,19,9,29,23,30,30,34,38,20,21,0,0);
INSERT INTO game VALUES(201810200NYK,7:30 PM October 20 2018,20,16,18,30,22,31,31,19,27,26,0,0);
INSERT INTO game VALUES(201810200PHI,7:30 PM October 20 2018,25,1,30,33,26,27,32,20,34,29,0,0);
INSERT INTO game VALUES(201810200POR,10:00 PM October 20 2018,26,30,22,37,38,24,22,28,32,26,0,0);
INSERT INTO game VALUES(201810200WAS,7:00 PM October 20 2018,27,28,22,32,28,31,24,33,33,27,0,0);
INSERT INTO game VALUES(201810210CLE,6:00 PM October 21 2018,8,13,34,26,26,25,24,40,28,41,0,0);
INSERT INTO game VALUES(201810210DEN,8:00 PM October 21 2018,21,7,17,30,33,20,25,24,21,28,0,0);
INSERT INTO game VALUES(201810210LAC,9:00 PM October 21 2018,24,29,29,25,39,22,24,29,31,28,0,0);
INSERT INTO game VALUES(201810210OKC,7:00 PM October 21 2018,18,2,32,24,34,30,34,34,29,34,0,0);
INSERT INTO game VALUES(201810220BOS,7:30 PM October 22 2018,25,20,19,26,25,20,28,20,27,18,0,0);
INSERT INTO game VALUES(201810220DAL,8:30 PM October 22 2018,14,10,31,28,29,27,28,33,23,25,0,0);
INSERT INTO game VALUES(201810220GSW,10:30 PM October 22 2018,23,21,32,38,36,17,23,24,34,22,0,0);
INSERT INTO game VALUES(201810220LAL,10:30 PM October 22 2018,26,15,26,34,36,32,40,25,34,29,14,15);
INSERT INTO game VALUES(201810220MIL,8:00 PM October 22 2018,16,3,33,38,17,36,29,23,35,26,0,0);
INSERT INTO game VALUES(201810220MIN,8:00 PM October 22 2018,17,12,25,25,22,29,28,21,24,18,0,0);
INSERT INTO game VALUES(201810220POR,10:00 PM October 22 2018,28,30,32,30,15,34,28,34,16,33,13,14);
INSERT INTO game VALUES(201810220TOR,7:30 PM October 22 2018,19,27,31,31,35,30,22,25,32,27,0,0);
INSERT INTO game VALUES(201810220UTA,9:00 PM October 22 2018,6,11,22,24,17,21,19,28,23,22,0,0);
INSERT INTO game VALUES(201810230DEN,9:00 PM October 23 2018,18,7,33,35,37,21,26,29,26,31,0,0);
INSERT INTO game VALUES(201810230DET,7:00 PM October 23 2018,1,22,27,34,26,33,28,36,30,26,13,12);
INSERT INTO game VALUES(201810230NOP,8:00 PM October 23 2018,29,5,27,32,32,25,26,36,22,25,0,0);
INSERT INTO game VALUES(201810240ATL,7:00 PM October 24 2018,10,8,22,26,32,31,42,16,29,17,0,0);
INSERT INTO game VALUES(201810240CHI,8:00 PM October 24 2018,19,14,24,30,34,24,27,26,29,28,0,0);
INSERT INTO game VALUES(201810240CLE,7:00 PM October 24 2018,4,13,17,28,17,24,24,21,38,19,0,0);
INSERT INTO game VALUES(201810240GSW,10:30 PM October 24 2018,28,21,46,34,35,29,37,34,26,25,0,0);
INSERT INTO game VALUES(201810240HOU,8:00 PM October 24 2018,11,24,29,15,22,23,24,28,23,25,0,0);
INSERT INTO game VALUES(201810240MIA,7:30 PM October 24 2018,16,9,16,31,45,18,27,18,20,22,0,0);
INSERT INTO game VALUES(201810240MIL,9:30 PM October 24 2018,1,3,22,49,21,31,34,30,17,27,0,0);
INSERT INTO game VALUES(201810240PHO,10:00 PM October 24 2018,15,23,30,24,32,27,32,44,30,25,0,0);
INSERT INTO game VALUES(201810240SAC,10:00 PM October 24 2018,6,18,19,25,27,26,28,24,19,21,0,0);
INSERT INTO game VALUES(201810240SAS,8:30 PM October 24 2018,17,26,22,28,21,25,28,34,26,28,0,0);
INSERT INTO game VALUES(201810240TOR,7:30 PM October 24 2018,12,27,26,31,26,29,19,29,26,31,0,0);
INSERT INTO game VALUES(201810250DET,7:00 PM October 25 2018,13,22,30,28,22,30,27,23,18,35,0,0);
INSERT INTO game VALUES(201810250LAL,10:30 PM October 25 2018,7,15,22,36,29,34,26,31,32,25,0,0);
INSERT INTO game VALUES(201810250OKC,8:00 PM October 25 2018,20,2,22,28,23,22,16,18,40,27,0,0);
INSERT INTO game VALUES(201810250ORL,7:00 PM October 25 2018,30,25,22,26,36,30,33,25,33,37,0,0);
INSERT INTO game VALUES(201810260CHO,7:00 PM October 26 2018,14,19,23,45,34,33,25,29,21,31,0,0);
INSERT INTO game VALUES(201810260HOU,8:00 PM October 26 2018,29,24,30,31,22,30,31,39,26,37,0,0);
INSERT INTO game VALUES(201810260MIN,8:00 PM October 26 2018,3,12,16,22,29,28,27,36,34,28,0,0);
INSERT INTO game VALUES(201810260NOP,8:00 PM October 26 2018,4,5,32,25,31,29,30,36,25,24,0,0);
INSERT INTO game VALUES(201810260NYK,7:30 PM October 26 2018,21,16,25,28,31,16,25,28,28,47,0,0);
INSERT INTO game VALUES(201810260SAC,10:00 PM October 26 2018,28,18,28,27,24,37,27,34,24,27,0,0);
INSERT INTO game VALUES(201810260TOR,7:30 PM October 26 2018,10,27,39,30,23,24,26,34,29,18,0,0);
INSERT INTO game VALUES(201810270ATL,7:30 PM October 27 2018,14,8,25,19,19,22,22,19,26,30,0,0);
INSERT INTO game VALUES(201810270CLE,7:30 PM October 27 2018,17,13,30,25,28,24,30,30,28,31,0,0);
INSERT INTO game VALUES(201810270DET,7:00 PM October 27 2018,20,22,21,20,26,22,30,33,21,25,0,0);
INSERT INTO game VALUES(201810270MEM,8:00 PM October 27 2018,23,6,26,42,19,30,18,25,28,25,0,0);
INSERT INTO game VALUES(201810270MIA,8:00 PM October 27 2018,30,9,33,24,32,31,22,20,37,32,0,0);
INSERT INTO game VALUES(201810270MIL,8:30 PM October 27 2018,25,3,30,35,28,20,25,26,17,23,0,0);
INSERT INTO game VALUES(201810270NOP,7:00 PM October 27 2018,11,5,31,18,33,29,28,36,38,30,0,0);
INSERT INTO game VALUES(201810270PHI,7:30 PM October 27 2018,19,1,32,31,20,22,28,34,23,18,0,0);
INSERT INTO game VALUES(201810270SAS,8:30 PM October 27 2018,15,26,29,25,33,23,36,24,28,18,0,0);
INSERT INTO game VALUES(201810280BRK,5:00 PM October 28 2018,21,4,29,20,28,37,32,31,30,27,0,0);
INSERT INTO game VALUES(201810280DAL,7:00 PM October 28 2018,11,10,19,27,31,27,26,24,32,31,0,0);
INSERT INTO game VALUES(201810280LAC,9:30 PM October 28 2018,28,29,28,41,28,39,20,34,23,27,0,0);
INSERT INTO game VALUES(201810280OKC,7:00 PM October 28 2018,23,2,30,32,34,21,20,28,28,34,0,0);
INSERT INTO game VALUES(201810290CHI,8:00 PM October 29 2018,21,14,28,22,39,35,44,48,33,24,0,0);
INSERT INTO game VALUES(201810290DEN,9:00 PM October 29 2018,5,7,20,38,26,32,24,21,31,35,0,0);
INSERT INTO game VALUES(201810290IND,7:00 PM October 29 2018,30,17,16,33,20,24,23,22,26,32,0,0);
INSERT INTO game VALUES(201810290MIA,7:30 PM October 29 2018,18,9,28,23,32,30,17,34,43,29,0,0);
INSERT INTO game VALUES(201810290MIL,8:00 PM October 29 2018,27,3,30,32,33,29,29,24,27,29,0,0);
INSERT INTO game VALUES(201810290MIN,8:00 PM October 29 2018,15,12,36,28,29,31,32,34,28,26,0,0);
INSERT INTO game VALUES(201810290NYK,7:30 PM October 29 2018,4,16,26,26,33,30,26,18,23,29,0,0);
INSERT INTO game VALUES(201810290PHI,7:00 PM October 29 2018,8,1,20,27,31,35,25,22,13,32,0,0);
INSERT INTO game VALUES(201810290SAS,8:30 PM October 29 2018,10,26,20,33,23,26,18,27,29,28,11,6);
INSERT INTO game VALUES(201810300BOS,7:30 PM October 30 2018,22,20,31,25,25,27,28,30,13,34,0,0);
INSERT INTO game VALUES(201810300CHO,7:00 PM October 30 2018,9,19,31,34,27,33,29,26,18,40,0,0);
INSERT INTO game VALUES(201810300CLE,7:00 PM October 30 2018,8,13,35,23,41,37,31,26,30,27,0,0);
INSERT INTO game VALUES(201810300HOU,8:00 PM October 30 2018,30,24,15,21,26,23,19,32,34,19,0,0);
INSERT INTO game VALUES(201810300MEM,8:00 PM October 30 2018,28,6,22,24,32,29,24,21,27,23,0,0);
INSERT INTO game VALUES(201810300OKC,8:00 PM October 30 2018,29,2,25,29,39,35,33,34,10,33,0,0);
INSERT INTO game VALUES(201810300ORL,7:00 PM October 30 2018,18,25,31,25,16,27,26,33,26,22,0,0);
INSERT INTO game VALUES(201810300TOR,7:30 PM October 30 2018,1,27,35,32,38,24,26,27,33,26,0,0);
INSERT INTO game VALUES(201810310BRK,7:30 PM October 31 2018,22,4,28,26,23,33,22,38,23,27,10,9);
INSERT INTO game VALUES(201810310CHI,8:00 PM October 31 2018,7,14,24,24,30,20,28,23,29,18,9,10);
INSERT INTO game VALUES(201810310GSW,10:30 PM October 31 2018,5,21,43,27,37,24,37,26,29,29,0,0);
INSERT INTO game VALUES(201810310LAL,10:30 PM October 31 2018,10,15,38,28,28,20,21,38,22,32,0,0);
INSERT INTO game VALUES(201810310MIN,8:00 PM October 31 2018,11,12,32,33,36,27,25,31,40,29,0,0);
INSERT INTO game VALUES(201810310NYK,8:00 PM October 31 2018,17,16,25,27,29,20,28,22,27,30,0,0);
INSERT INTO game VALUES(201810310PHO,10:30 PM October 31 2018,26,23,15,24,27,24,28,32,34,26,0,0);

In [120]:
# builg player stats
for index, el in player.iterrows():
    #print(el)
    print('INSERT INTO player_game_stats VALUES(' + 
          el.game_id + ',' +
        str(player_look_up_table[el['name']]) + ',' +
        str(team_look_up_table[el['team']]) + ',' +
        el.mp + ',' +
        str(el.fg) + ','+ # field goal made
        str(el.fga) + ','+ # field goal attempts
        str(el.tp) + ','+
        str(el.tpa) + ','+
        str(el.ft)+ ','+
        str(el.fta)+ ','+
        str(el.orb)+ ','+
        str(el.drb)+ ','+
        str(el.ast)+ ','+
        str(el.stl)+ ','+
        str(el.blk)+ ','+
        str(el.tov)+ ','+
        str(el.pf)+ ','+
        str(el.pts)+ ','+
        str(el.pm)+ ','+
        str(el.orbp)+ ','+
        str(el.drbp)+ ','+
        str(el.trbp)+ ','+
        str(el.astp)+ ','+
        str(el.stlp)+ ','+
        str(el.blkp)+ ','+
        str(el.tovp)+ ','+
        str(el.usgp)+ ','+
        str(el.ortg)+ ','+
        str(el.drtg)+ ');')

INSERT INTO player_game_stats VALUES(201810160BOS,1,1,42:45,7.0,14.0,0.0,0.0,5.0,10.0,3.0,12.0,8.0,4.0,2.0,3.0,5.0,19.0,-8.0,6.9,25.4,16.5,34.4,4.3,3.7,14.0,21.2,104.0,90.0);
INSERT INTO player_game_stats VALUES(201810160BOS,2,1,36:49,9.0,21.0,1.0,4.0,4.0,5.0,2.0,8.0,2.0,1.0,2.0,5.0,3.0,23.0,-8.0,5.3,19.7,12.8,11.7,1.3,4.3,17.7,32.5,84.0,98.0);
INSERT INTO player_game_stats VALUES(201810160BOS,3,1,34:12,3.0,10.0,2.0,7.0,0.0,0.0,1.0,5.0,0.0,2.0,1.0,2.0,1.0,8.0,-11.0,2.9,13.2,8.3,0.0,2.7,2.3,16.7,14.9,67.0,99.0);
INSERT INTO player_game_stats VALUES(201810160BOS,4,1,24:20,2.0,7.0,0.0,0.0,1.0,2.0,0.0,3.0,2.0,1.0,0.0,3.0,1.0,5.0,-16.0,0.0,11.2,5.8,13.1,1.9,0.0,27.6,19.0,52.0,103.0);
INSERT INTO player_game_stats VALUES(201810160BOS,5,1,22:55,3.0,8.0,0.0,4.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,3.0,5.0,6.0,-4.0,0.0,23.7,12.3,7.6,0.0,0.0,27.3,20.4,55.0,103.0);
INSERT INTO player_game_stats VALUES(201810160BOS,6,1,29:46,7.0,17.0,2.0,8.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,16.0,-10.0,0.0,6.1,3.2,7.1,0.0,0.0,0.0,24.2,92.0,109.0);
INSERT INTO player_game_stats VALUES(201810160BOS,7,1,22:26,2.0,5.0,0.0,1.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,3.0,4.0,-11.0,0.0,4.0,2.1,21.6,0.0,0.0,0.0,9.5,97.0,109.0);
INSERT INTO player_game_stats VALUES(201810160BOS,8,1,12:42,0.0,4.0,0.0,2.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,-8.0,0.0,7.1,3.7,0.0,0.0,0.0,0.0,16.3,23.0,108.0);
INSERT INTO player_game_stats VALUES(201810160BOS,9,1,11:11,1.0,1.0,0.0,0.0,3.0,4.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,5.0,-10.0,0.0,24.3,12.6,14.4,0.0,0.0,0.0,10.5,193.0,103.0);
INSERT INTO player_game_stats VALUES(201810160BOS,10,1,1:27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,0.0,0.0,111.0);
INSERT INTO player_game_stats VALUES(201810160BOS,11,1,1:27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,0.0,0.0,111.0);
INSERT INTO player_game_stats VALUES(201810160BOS,12,1,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810160BOS,13,1,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810160BOS,14,20,29:57,4.0,7.0,0.0,1.0,1.0,1.0,0.0,4.0,2.0,0.0,4.0,3.0,1.0,9.0,9.0,0.0,13.1,6.3,9.0,0.0,10.5,28.7,14.3,90.0,80.0);
INSERT INTO player_game_stats VALUES(201810160BOS,15,20,29:00,2.0,14.0,1.0,8.0,2.0,2.0,0.0,4.0,7.0,0.0,0.0,3.0,1.0,7.0,9.0,0.0,13.5,6.5,29.9,0.0,0.0,16.8,25.3,63.0,89.0);
INSERT INTO player_game_stats VALUES(201810160BOS,16,20,28:56,9.0,17.0,1.0,5.0,4.0,5.0,2.0,7.0,3.0,1.0,0.0,1.0,2.0,23.0,6.0,6.3,23.7,14.6,18.4,1.6,0.0,5.0,28.6,125.0,83.0);
INSERT INTO player_game_stats VALUES(201810160BOS,17,20,28:23,5.0,13.0,1.0,3.0,1.0,2.0,3.0,2.0,2.0,0.0,0.0,2.0,4.0,12.0,11.0,9.6,6.9,8.3,10.1,0.0,0.0,12.6,22.9,91.0,89.0);
INSERT INTO player_game_stats VALUES(201810160BOS,18,20,24:37,4.0,12.0,1.0,3.0,1.0,2.0,2.0,3.0,0.0,4.0,0.0,0.0,1.0,10.0,10.0,7.4,11.9,9.6,0.0,7.5,0.0,0.0,21.4,90.0,74.0);
INSERT INTO player_game_stats VALUES(201810160BOS,19,20,26:31,5.0,10.0,1.0,2.0,0.0,0.0,0.0,8.0,1.0,0.0,1.0,1.0,0.0,11.0,22.0,0.0,29.6,14.2,5.5,0.0,3.0,9.1,17.0,102.0,84.0);
INSERT INTO player_game_stats VALUES(201810160BOS,20,20,25:01,2.0,4.0,2.0,4.0,1.0,2.0,0.0,3.0,3.0,0.0,0.0,2.0,2.0,7.0,3.0,0.0,11.7,5.6,15.1,0.0,0.0,29.1,11.3,109.0,89.0);
INSERT INTO player_game_stats VALUES(201810160BOS,21,20,20:30,7.0,12.0,2.0,7.0,0.0,0.0,2.0,8.0,0.0,2.0,0.0,1.0,5.0,16.0,3.0,8.8,38.2,23.0,0.0,4.5,0.0,7.7,26.0,122.0,74.0);
INSERT INTO player_game_stats VALUES(201810160BOS,22,20,19:14,3.0,7.0,2.0,4.0,0.0,0.0,3.0,1.0,3.0,0.0,0.0,1.0,3.0,8.0,8.0,14.1,5.1,9.8,21.7,0.0,0.0,12.5,17.0,124.0,89.0);
INSERT INTO player_game_stats VALUES(201810160BOS,23,20,4:08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,23.7,11.4,0.0,0.0,0.0,nan,0.0,0.0,86.0);
INSERT INTO player_game_stats VALUES(201810160BOS,24,20,1:27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,67.6,32.5,0.0,0.0,0.0,nan,0.0,0.0,80.0);
INSERT INTO player_game_stats VALUES(201810160BOS,25,20,1:27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,0.0,0.0,91.0);
INSERT INTO player_game_stats VALUES(201810160BOS,26,20,0:49,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,100.0,57.6,0.0,0.0,0.0,0.0,50.2,200.0,71.0);
INSERT INTO player_game_stats VALUES(201810160GSW,27,2,37:24,9.0,23.0,4.0,12.0,5.0,8.0,0.0,2.0,5.0,4.0,0.0,5.0,3.0,27.0,-16.0,0.0,5.6,2.5,29.9,5.0,0.0,15.9,33.4,93.0,104.0);
INSERT INTO player_game_stats VALUES(201810160GSW,28,2,35:36,6.0,12.0,0.0,0.0,5.0,8.0,4.0,7.0,4.0,2.0,0.0,2.0,3.0,17.0,-6.0,9.5,20.5,14.4,21.7,2.6,0.0,11.4,19.5,114.0,103.0);
INSERT INTO player_game_stats VALUES(201810160GSW,29,2,34:05,7.0,19.0,2.0,6.0,5.0,6.0,2.0,6.0,6.0,3.0,1.0,3.0,4.0,21.0,-7.0,4.9,18.4,10.9,36.5,4.1,2.0,12.2,28.6,102.0,100.0);
INSERT INTO player_game_stats VALUES(201810160GSW,30,2,26:31,0.0,2.0,0.0,2.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,6.4,7.9,7.0,5.5,0.0,0.0,33.3,4.5,48.0,114.0);
INSERT INTO player_game_stats VALUES(201810160GSW,31,2,18:53,2.0,9.0,1.0,4.0,2.0,3.0,3.0,2.0,0.0,1.0,1.0,1.0,0.0,7.0,3.0,13.4,11.1,12.3,0.0,2.5,3.7,8.8,23.7,80.0,105.0);
INSERT INTO player_game_stats VALUES(201810160GSW,32,2,29:07,2.0,7.0,1.0,4.0,2.0,4.0,2.0,0.0,2.0,0.0,3.0,0.0,1.0,7.0,-11.0,5.8,0.0,3.2,11.1,0.0,7.2,0.0,11.9,104.0,114.0);
INSERT INTO player_game_stats VALUES(201810160GSW,33,2,23:28,3.0,8.0,2.0,6.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,8.0,-5.0,0.0,8.9,4.0,0.0,0.0,0.0,0.0,13.5,104.0,114.0);
INSERT INTO player_game_stats VALUES(201810160GSW,34,2,13:55,1.0,5.0,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,0.0,2.0,0.0,6.0,-1.0,0.0,22.5,10.0,11.7,0.0,0.0,21.7,26.2,76.0,108.0);
INSERT INTO player_game_stats VALUES(201810160GSW,35,2,12:24,1.0,2.0,0.0,0.0,1.0,2.0,3.0,4.0,1.0,1.0,1.0,0.0,3.0,3.0,-2.0,20.4,33.7,26.3,13.3,3.8,5.6,0.0,9.2,142.0,92.0);
INSERT INTO player_game_stats VALUES(201810160GSW,36,2,8:37,2.0,4.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,2.0,4.0,5.0,0.0,12.1,5.4,25.5,5.4,0.0,0.0,20.4,99.0,100.0);
INSERT INTO player_game_stats VALUES(201810160GSW,37,2,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810160GSW,38,2,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810160GSW,39,2,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810160GSW,40,21,37:43,9.0,21.0,0.0,5.0,9.0,10.0,1.0,7.0,6.0,1.0,1.0,3.0,4.0,27.0,14.0,2.8,15.6,9.9,25.0,1.2,2.4,10.6,29.2,116.0,98.0);
INSERT INTO player_game_stats VALUES(201810160GSW,41,21,36:37,11.0,20.0,5.0,9.0,5.0,5.0,0.0,8.0,9.0,1.0,0.0,3.0,4.0,32.0,15.0,0.0,18.4,10.2,42.8,1.3,0.0,11.9,26.7,141.0,97.0);
INSERT INTO player_game_stats VALUES(201810160GSW,42,21,34:59,5.0,20.0,1.0,8.0,3.0,3.0,1.0,3.0,0.0,0.0,0.0,2.0,3.0,14.0,2.0,3.0,7.2,5.3,0.0,0.0,0.0,8.6,25.8,75.0,106.0);
INSERT INTO player_game_stats VALUES(201810160GSW,43,21,32:45,1.0,6.0,0.0,1.0,0.0,0.0,1.0,12.0,5.0,3.0,0.0,6.0,3.0,2.0,2.0,3.2,30.9,18.5,18.1,4.3,0.0,50.0,14.2,42.0,85.0);
INSERT INTO player_game_stats VALUES(201810160GSW,44,21,26:33,6.0,7.0,0.0,0.0,0.0,0.0,2.0,1.0,2.0,0.0,3.0,2.0,4.0,12.0,-1.0,7.9,3.2,5.3,11.6,0.0,10.0,22.2,13.1,130.0,102.0);
INSERT INTO player_game_stats VALUES(201810160GSW,45,21,18:04,5.0,11.0,0.0,0.0,0.0,0.0,8.0,2.0,2.0,1.0,2.0,1.0,4.0,10.0,23.0,46.2,9.3,25.8,18.5,2.6,9.8,8.3,25.7,117.0,93.0);
INSERT INTO player_game_stats VALUES(201810160GSW,46,21,14:34,3.0,5.0,0.0,0.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,1.0,2.0,6.0,-3.0,14.3,5.8,9.6,10.3,3.2,0.0,16.7,16.0,114.0,99.0);
INSERT INTO player_game_stats VALUES(201810160GSW,47,21,13:12,1.0,2.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,2.0,2.0,3.0,-7.0,7.9,6.4,7.1,9.5,0.0,0.0,50.0,11.7,81.0,106.0);
INSERT INTO player_game_stats VALUES(201810160GSW,48,21,10:23,1.0,2.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,16.2,9.0,24.7,0.0,0.0,0.0,7.5,139.0,102.0);
INSERT INTO player_game_stats VALUES(201810160GSW,49,21,6:39,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-6.0,15.7,12.7,14.0,0.0,0.0,13.4,nan,0.0,220.0,96.0);
INSERT INTO player_game_stats VALUES(201810160GSW,50,21,6:10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,41.0,22.7,0.0,0.0,0.0,100.0,6.3,0.0,87.0);
INSERT INTO player_game_stats VALUES(201810160GSW,51,21,2:21,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.5,0.0,110.0);
INSERT INTO player_game_stats VALUES(201810160GSW,52,21,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170CHO,53,3,38:01,4.0,9.0,2.0,6.0,0.0,0.0,0.0,3.0,6.0,1.0,0.0,4.0,3.0,10.0,1.0,0.0,6.9,3.9,20.5,1.2,0.0,30.8,14.3,94.0,112.0);
INSERT INTO player_game_stats VALUES(201810170CHO,54,3,34:46,9.0,21.0,0.0,3.0,7.0,12.0,3.0,15.0,8.0,0.0,1.0,8.0,5.0,25.0,11.0,9.6,37.7,25.4,37.3,0.0,2.6,23.3,41.2,91.0,105.0);
INSERT INTO player_game_stats VALUES(201810170CHO,55,3,33:32,7.0,13.0,3.0,5.0,0.0,0.0,2.0,2.0,3.0,0.0,1.0,2.0,4.0,17.0,4.0,6.7,5.2,5.8,13.4,0.0,2.7,13.3,18.7,122.0,113.0);
INSERT INTO player_game_stats VALUES(201810170CHO,56,3,32:46,7.0,14.0,3.0,6.0,2.0,2.0,1.0,8.0,4.0,2.0,1.0,2.0,3.0,19.0,2.0,3.4,21.3,13.5,18.5,2.9,2.7,11.8,21.5,124.0,102.0);
INSERT INTO player_game_stats VALUES(201810170CHO,57,3,21:27,4.0,7.0,2.0,5.0,4.0,4.0,0.0,3.0,1.0,1.0,0.0,2.0,3.0,14.0,8.0,0.0,12.2,6.9,6.8,2.2,0.0,18.6,21.0,130.0,108.0);
INSERT INTO player_game_stats VALUES(201810170CHO,58,3,29:00,6.0,9.0,1.0,3.0,0.0,0.0,1.0,8.0,2.0,0.0,0.0,0.0,6.0,13.0,-10.0,3.8,24.1,15.2,10.3,0.0,0.0,0.0,13.0,153.0,110.0);
INSERT INTO player_game_stats VALUES(201810170CHO,59,3,22:04,3.0,6.0,2.0,4.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,8.0,-9.0,5.1,4.0,4.4,6.1,2.1,0.0,14.3,13.3,120.0,111.0);
INSERT INTO player_game_stats VALUES(201810170CHO,60,3,12:00,1.0,3.0,0.0,0.0,2.0,2.0,2.0,4.0,0.0,0.0,1.0,2.0,1.0,4.0,2.0,18.6,29.1,24.5,0.0,0.0,7.4,34.0,20.5,87.0,103.0);
INSERT INTO player_game_stats VALUES(201810170CHO,61,3,11:20,0.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,9.8,7.7,8.6,10.1,0.0,0.0,0.0,7.4,65.0,115.0);
INSERT INTO player_game_stats VALUES(201810170CHO,62,3,4:57,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,-3.0,0.0,17.6,9.9,0.0,0.0,0.0,0.0,8.4,300.0,113.0);
INSERT INTO player_game_stats VALUES(201810170CHO,63,3,0:07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,0.0,0.0,117.0);
INSERT INTO player_game_stats VALUES(201810170CHO,64,3,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170CHO,65,3,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170CHO,66,19,38:39,15.0,29.0,7.0,13.0,4.0,5.0,1.0,1.0,4.0,2.0,0.0,3.0,0.0,41.0,-1.0,2.3,2.9,2.5,22.2,2.4,0.0,8.8,37.7,121.0,114.0);
INSERT INTO player_game_stats VALUES(201810170CHO,67,19,31:49,2.0,8.0,1.0,4.0,0.0,0.0,1.0,6.0,3.0,2.0,2.0,2.0,1.0,5.0,-4.0,2.7,21.1,10.8,11.9,2.9,5.9,20.0,13.4,71.0,104.0);
INSERT INTO player_game_stats VALUES(201810170CHO,68,19,25:51,2.0,7.0,1.0,6.0,0.0,2.0,1.0,8.0,1.0,0.0,4.0,1.0,2.0,5.0,-4.0,3.4,34.5,17.1,5.0,0.0,14.6,11.3,14.6,69.0,102.0);
INSERT INTO player_game_stats VALUES(201810170CHO,69,19,21:06,1.0,1.0,1.0,1.0,2.0,2.0,0.0,3.0,1.0,1.0,0.0,0.0,3.0,5.0,-11.0,0.0,15.9,7.0,5.9,2.2,0.0,0.0,3.8,266.0,110.0);
INSERT INTO player_game_stats VALUES(201810170CHO,70,19,20:48,4.0,11.0,2.0,4.0,0.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,2.0,10.0,-6.0,8.4,0.0,4.7,7.3,2.3,0.0,0.0,22.5,104.0,114.0);
INSERT INTO player_game_stats VALUES(201810170CHO,71,19,33:35,7.0,16.0,4.0,8.0,0.0,0.0,0.0,4.0,2.0,1.0,2.0,0.0,1.0,18.0,5.0,0.0,13.3,5.8,9.2,1.4,5.6,0.0,20.3,115.0,110.0);
INSERT INTO player_game_stats VALUES(201810170CHO,72,19,21:38,3.0,6.0,0.0,0.0,4.0,6.0,3.0,3.0,1.0,0.0,1.0,1.0,3.0,10.0,3.0,12.1,15.5,13.6,6.5,0.0,4.4,10.4,19.0,123.0,113.0);
INSERT INTO player_game_stats VALUES(201810170CHO,73,19,19:48,4.0,8.0,0.0,0.0,0.0,0.0,0.0,3.0,7.0,0.0,0.0,2.0,2.0,8.0,5.0,0.0,16.9,7.4,54.2,0.0,0.0,20.0,21.5,107.0,115.0);
INSERT INTO player_game_stats VALUES(201810170CHO,74,19,14:30,0.0,1.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,1.0,6.0,0.0,0.0,0.0,8.1,0.0,0.0,34.7,8.5,54.0,119.0);
INSERT INTO player_game_stats VALUES(201810170CHO,75,19,12:16,3.0,5.0,0.0,1.0,3.0,5.0,1.0,4.0,0.0,1.0,0.0,1.0,3.0,9.0,2.0,7.1,36.4,20.0,0.0,3.8,0.0,12.2,28.5,113.0,101.0);
INSERT INTO player_game_stats VALUES(201810170CHO,76,19,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170CHO,77,19,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170CHO,78,19,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,79,4,37:08,6.0,14.0,1.0,7.0,0.0,0.0,0.0,6.0,5.0,1.0,0.0,2.0,2.0,13.0,-2.0,0.0,16.2,9.1,20.0,1.3,0.0,12.5,19.0,89.0,105.0);
INSERT INTO player_game_stats VALUES(201810170DET,80,4,35:51,0.0,5.0,0.0,4.0,1.0,2.0,2.0,1.0,3.0,3.0,0.0,0.0,5.0,1.0,-8.0,7.2,2.8,4.7,10.0,4.0,0.0,0.0,7.2,64.0,104.0);
INSERT INTO player_game_stats VALUES(201810170DET,81,4,33:59,10.0,18.0,0.0,2.0,7.0,8.0,1.0,3.0,4.0,1.0,1.0,3.0,2.0,27.0,-10.0,3.8,8.8,6.6,21.8,1.4,2.1,12.2,31.9,114.0,106.0);
INSERT INTO player_game_stats VALUES(201810170DET,82,4,30:09,6.0,10.0,2.0,3.0,3.0,4.0,2.0,8.0,0.0,0.0,4.0,2.0,4.0,17.0,-9.0,8.6,26.5,18.7,0.0,0.0,9.4,14.5,20.2,118.0,98.0);
INSERT INTO player_game_stats VALUES(201810170DET,83,4,24:58,3.0,9.0,1.0,4.0,1.0,2.0,0.0,2.0,5.0,1.0,0.0,2.0,1.0,8.0,-9.0,0.0,8.0,4.5,28.1,1.9,0.0,16.8,21.0,82.0,107.0);
INSERT INTO player_game_stats VALUES(201810170DET,84,4,32:17,10.0,18.0,0.0,3.0,3.0,5.0,0.0,4.0,6.0,1.0,0.0,4.0,1.0,23.0,6.0,0.0,12.4,7.0,35.5,1.5,0.0,16.5,33.1,98.0,106.0);
INSERT INTO player_game_stats VALUES(201810170DET,85,4,17:36,4.0,4.0,0.0,0.0,0.0,1.0,0.0,7.0,3.0,1.0,0.0,2.0,2.0,8.0,8.0,0.0,39.8,22.5,28.1,2.7,0.0,31.1,16.2,116.0,93.0);
INSERT INTO player_game_stats VALUES(201810170DET,86,4,17:25,0.0,2.0,0.0,2.0,0.0,0.0,0.0,2.0,1.0,1.0,0.0,1.0,4.0,0.0,6.0,0.0,11.5,6.5,6.9,2.8,0.0,33.3,7.6,18.0,104.0);
INSERT INTO player_game_stats VALUES(201810170DET,87,4,10:37,1.0,2.0,1.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,3.0,3.0,0.0,9.4,5.3,12.7,0.0,0.0,33.3,12.5,94.0,110.0);
INSERT INTO player_game_stats VALUES(201810170DET,88,4,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,89,4,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,90,4,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,91,22,35:01,7.0,20.0,2.0,9.0,3.0,3.0,1.0,1.0,4.0,1.0,0.0,2.0,1.0,19.0,3.0,2.9,3.7,3.2,18.6,1.4,0.0,8.6,27.6,97.0,102.0);
INSERT INTO player_game_stats VALUES(201810170DET,92,22,34:17,8.0,17.0,1.0,1.0,9.0,11.0,2.0,6.0,6.0,0.0,0.0,1.0,0.0,26.0,8.0,5.8,22.7,13.2,30.2,0.0,0.0,4.4,27.6,133.0,103.0);
INSERT INTO player_game_stats VALUES(201810170DET,93,22,32:12,10.0,21.0,1.0,3.0,3.0,4.0,9.0,11.0,2.0,0.0,1.0,4.0,5.0,24.0,-9.0,28.0,44.3,35.1,12.4,0.0,2.7,14.9,34.5,106.0,98.0);
INSERT INTO player_game_stats VALUES(201810170DET,94,22,19:21,3.0,5.0,1.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,1.0,1.0,7.0,-1.0,0.0,26.8,11.7,0.0,0.0,4.5,16.7,12.9,111.0,99.0);
INSERT INTO player_game_stats VALUES(201810170DET,95,22,18:52,0.0,3.0,0.0,2.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,1.0,4.0,0.0,6.0,0.0,13.8,6.0,6.5,0.0,4.6,25.0,8.8,14.0,99.0);
INSERT INTO player_game_stats VALUES(201810170DET,96,22,33:00,2.0,5.0,0.0,3.0,2.0,2.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,6.0,-5.0,0.0,11.8,5.1,4.0,0.0,0.0,0.0,7.4,120.0,104.0);
INSERT INTO player_game_stats VALUES(201810170DET,97,22,28:45,5.0,11.0,1.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,1.0,4.0,11.0,4.0,0.0,0.0,0.0,16.3,0.0,0.0,8.3,17.3,104.0,105.0);
INSERT INTO player_game_stats VALUES(201810170DET,98,22,20:04,2.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,2.4,4.3,25.0,8.3,93.0,97.0);
INSERT INTO player_game_stats VALUES(201810170DET,99,22,14:43,2.0,6.0,0.0,0.0,2.0,2.0,2.0,5.0,4.0,2.0,1.0,2.0,5.0,6.0,9.0,13.6,44.1,26.9,40.2,6.5,5.9,22.5,25.0,97.0,81.0);
INSERT INTO player_game_stats VALUES(201810170DET,100,22,3:45,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.8,0.0,50.0,22.1,0.0,79.0);
INSERT INTO player_game_stats VALUES(201810170DET,101,22,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,102,22,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,103,22,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,104,22,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170DET,105,22,0:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
INSERT INTO player_game_stats VALUES(201810170HOU,106,5,39:07,13.0,21.0,0.0,0.0,6.0,7.0,2.0,14.0,8.0,3.0,3.0,1.0,5.0,32.0,23.0,5.7,35.8,21.6,27.2,3.6,8.4,4.0,25.7,146.0,95.0);
INSERT INTO player_game_stats VALUES(201810170HOU,107,5,38:16,5.0,12.0,0.0,6.0,0.0,0.0,0.0,3.0,8.0,2.0,0.0,3.0,3.0,10.0,26.0,0.0,7.8,4.1,21.9,2.4,0.0,20.0,15.7,94.0,110.0);
INSERT INTO player_game_stats VALUES(201810170HOU,108,5,36:52,5.0,13.0,0.0,2.0,0.0,2.0,1.0,9.0,10.0,1.0,0.0,1.0,3.0,10.0,23.0,3.0,24.4,14.3,28.6,1.3,0.0,6.7,16.2,106.0,109.0);
INSERT INTO player_game_stats VALUES(201810170HOU,109,5,33:44,8.0,12.0,1.0,3.0,4.0,4.0,2.0,1.0,2.0,1.0,0.0,2.0,5.0,21.0,30.0,6.6,3.0,4.7,7.0,1.4,0.0,12.7,18.7,140.0,113.0);
INSERT INTO player_game_stats VALUES(201810170HOU,110,5,29:54,11.0,20.0,6.0,8.0,2.0,3.0,7.0,3.0,3.0,0.0,0.0,1.0,1.0,30.0,14.0,26.1,10.0,17.6,14.0,0.0,0.0,4.5,29.9,148.0,115.0);
INSERT INTO player_game_stats VALUES(201810170HOU,111,5,23:49,9.0,15.0,2.0,4.0,5.0,6.0,2.0,6.0,3.0,0.0,0.0,0.0,4.0,25.0,5.0,9.4,25.2,17.7,17.9,0.0,0.0,0.0,29.7,156.0,111.0);
INSERT INTO player_game_stats VALUES(201810170HOU,112,5,19:56,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,2.0,0.0,-5.0,0.0,0.0,0.0,4.6,2.3,0.0,50.0,8.0,17.0,112.0);
INSERT INTO player_game_stats VALUES(201810170HOU,113,5,12:02,1.0,3.0,1.0,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,2.0,3.0,-13.0,0.0,16.6,8.8,8.3,0.0,0.0,0.0,10.0,123.0,113.0);
INSERT INTO player_game_stats VALUES(201810170HOU,114,5,1:35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,0.0,0.0,118.0);
INSERT INTO player_game_stats VALUES(201810170HOU,115,5,1:35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,50.7,0.0,118.0);
INSERT INTO player_game_stats VALUES(201810170HOU,116,5,1:35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,100.0,66.6,0.0,0.0,0.0,nan,0.0,0.0,88.0);
INSERT INTO player_game_stats VALUES(201810170HOU,117,5,1:35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,nan,0.0,0.0,118.0);

KeyError: 'Luc Mbah a Moute'